import 'package:cloud_firestore/cloud_firestore.dart';

//DO NOT CALL UNLESS YOU KNOW WHAT THIS FUNCTION DOES AND WHY.
//Loads Firestore database with the JSON below.
void loadBooks() async {
  // opens a connection to the database
  final db = FirebaseFirestore.instance;

  // Stores hardcoded book values in the database
  final List<Map<String, dynamic>> books = [
    {'title': 'Harry Potter and the Sorcerer\'s Stone',
      'author': 'J. K. Rowling',
      'year': '1997',
      'description': 'An orphan gets kidnapped by a large bearded man who tells him he\'s a wizard.',
      'picture':''},
    {'title': 'Sean\'s Autobiography',
    'author': 'Sean Boden',
    'year': '2021',
    'description': 'This is the story all about how my life got turned, flipped upside down.',
    'picture':''},
    {'title': 'Title McTitleron',
      'author': 'Test Testertron',
      'year': '1999',
      'description': 'This is a test description.',
      'picture':''},
    {'title': 'Harry Potter and the Chamber of Secrets',
      'author': 'J. K. Rowling',
      'year': '1998',
      'description': '',
      'picture':''},
    {'title': 'Harry Potter and the Prisoner of Azkaban',
      'author': 'J. K. Rowling',
      'year': '1999',
      'description': '',
      'picture':''},
    {'title': 'Harry Potter and the Goblet of Fire',
      'author': 'J. K. Rowling',
      'year': '2000',
      'description': '',
      'picture':''},
    {'title': 'Harry Potter and the Order of the Phoenix',
      'author': 'J. K. Rowling',
      'year': '2003',
      'description': '',
      'picture':''},
    {'title': 'Harry Potter and the Half-Blood Prince',
      'author': 'J. K. Rowling',
      'year': '2005',
      'description': '',
      'picture':''},
    {'title': 'Harry Potter and the Deathly Hallows',
      'author': 'J. K. Rowling',
      'year': '2007',
      'description': '',
      'picture':''},
    {'title': 'Wheel of time: The Eye of the World',
      'author': 'Robert Jordan',
      'year': '1990',
      'description': '',
      'picture':''},
    {'title': 'Wheel of time: The Great Hunt',
      'author': 'Robert Jordan',
      'year': '1990',
      'description': '',
      'picture':''},
    {'title': 'Wheel of time: The Dragon Reborn',
      'author': 'Robert Jordan',
      'year': '1991',
      'description': '',
      'picture':''},
    {'title': 'Wheel of time:The Shadow Rising',
      'author': 'Robert Jordan',
      'year': '1992',
      'description': '',
      'picture':''},
    {'title': 'Wheel of time: The Fires of Heaven',
      'author': 'Robert Jordan',
      'year': '1993',
      'description': '',
      'picture':''},
    {'title': 'Wheel of time: Lord of Chaos',
      'author': 'Robert Jordan',
      'year': '1994',
      'description': '',
      'picture':''},
    {'title': 'Wheel of time: A Crown of Swords',
      'author': 'Robert Jordan',
      'year': '1994',
      'description': '',
      'picture':''},
    {'title': 'Wheel of time: The Path of Daggers',
      'author': 'Robert Jordan',
      'year': '1998',
      'description': '',
      'picture':''},
    {'title': 'Wheel of time: Winter\'s Heart',
      'author': 'Robert Jordan',
      'year': '2000',
      'description': '',
      'picture':''},
    {'title': 'Wheel of time: Crossroads of Twilight',
      'author': 'Robert Jordan',
      'year': '2003',
      'description': '',
      'picture':''},
    {'title': 'Wheel of time: Knife of Dreams',
      'author': 'Robert Jordan',
      'year': '2005',
      'description': '',
      'picture':''},
    {'title': 'Wheel of time: The Gathering Storm',
      'author': 'Robert Jordan and Brandon Sanderson',
      'year': '2009',
      'description': '',
      'picture':''},
    {'title': 'Wheel of time: Towers of Midnight',
      'author': 'Robert Jordan and Brandon Sanderson',
      'year': '2010',
      'description': '',
      'picture':''},
    {'title': 'Wheel of time: A Memory of Light',
      'author': 'Robert Jordan and Brandon Sanderson',
      'year': '2013',
      'description': '',
      'picture':''},
    {'title': 'Eragon',
      'author': 'Christopher Paolini',
      'year': '2001',
      'description': '',
      'picture':''},
    {'title': 'Eragon: Eldest',
      'author': 'Christopher Paolini',
      'year': '2005',
      'description': '',
      'picture':''},
    {'title': 'Eragon: Brisingr',
      'author': 'Christopher Paolini',
      'year': '2008',
      'description': '',
      'picture':''},
    {'title': 'Eragon: Inheritance',
      'author': 'Christopher Paolini',
      'year': '2011',
      'description': '',
      'picture':''},
    {'title': 'The Fellowship of the Ring',
      'author': 'J. R. R. Tolkien',
      'year': '1954',
      'description': '',
      'picture':''},
    {'title': 'The Two Towers',
      'author': 'J. R. R. Tolkien',
      'year': '1954',
      'description': '',
      'picture':''},
    {'title': 'The Return of the King',
      'author': 'J. R. R. Tolkien',
      'year': '1955',
      'description': '',
      'picture':''},
    {'title': 'Ringworld',
      'author': 'Larry Niven',
      'year': '1970',
      'description': '',
      'picture':''},
    {'title': 'Halo: The Fall of Reach',
      'author': 'Eric Nylund',
      'year': '2001',
      'description': '',
      'picture':''},
    {'title': 'Halo: The Flood',
      'author': 'William C. Dietz',
      'year': '2003',
      'description': '',
      'picture':''},
    {'title': 'Halo: First Strike',
      'author': 'Eric Nylund',
      'year': '2003',
      'description': '',
      'picture':''},
    {'title': 'Halo: Ghosts of Onyx',
      'author': 'Eric Nylund',
      'year': '2006',
      'description': '',
      'picture':''},
    {'title': 'Red Rising',
      'author': 'Pierce Brown',
      'year': '2014',
      'description': '',
      'picture':''},
    {'title': 'Red Rising: Golden Son',
      'author': 'Pierce Brown',
      'year': '2015',
      'description': '',
      'picture':''},
    {'title': 'Red Rising: Morning Star',
      'author': 'Pierce Brown',
      'year': '2016',
      'description': '',
      'picture':''},
    {'title': 'Dune',
      'author': 'Frank Herbert',
      'year': '1965',
      'description': '',
      'picture':''},
    {'title': 'Dune Messiah',
      'author': 'Frank Herbert',
      'year': '1969',
      'description': '',
      'picture':''},
    {'title': 'Children of Dune',
      'author': 'Frank Herbert',
      'year': '1976',
      'description': '',
      'picture':''},
    {'title': 'God Emperor of Dune',
      'author': 'Frank Herbert',
      'year': '1981',
      'description': '',
      'picture':''},
    {'title': 'Heretics of Dune',
      'author': 'Frank Herbert',
      'year': '1984',
      'description': '',
      'picture':''},
    {'title': 'Chapterhouse: Dune',
      'author': 'Frank Herbert',
      'year': '1985',
      'description': '',
      'picture':''},
    {'title': 'A Game of Thrones',
      'author': 'George R. R. Martin',
      'year': '1996',
      'description': '',
      'picture':''},
    {'title': 'A Clash of Kings',
      'author': 'George R. R. Martin',
      'year': '1999',
      'description': '',
      'picture':''},
    {'title': 'A Storm of Swords',
      'author': 'George R. R. Martin',
      'year': '2000',
      'description': '',
      'picture':''},
    {'title': 'A Feast for Crows',
      'author': 'George R. R. Martin',
      'year': '2005',
      'description': '',
      'picture':''},
    {'title': 'A Dance with Dragons',
      'author': 'George R. R. Martin',
      'year': '2011',
      'description': '',
      'picture':''},
    {'title': 'A Wizard of Earthsea',
      'author': 'Ursula K. Le Guin',
      'year': '1968',
      'description': '',
      'picture':''},
    {'title': 'The Tombs of Atuan',
      'author': 'Ursula K. Le Guin',
      'year': '1970',
      'description': '',
      'picture':''},
    {'title': 'The Farthest Shore',
      'author': 'Ursula K. Le Guin',
      'year': '1972',
      'description': '',
      'picture':''},
    {'title': 'Tehanu',
      'author': 'Ursula K. Le Guin',
      'year': '1990',
      'description': '',
      'picture':''},
    {'title': 'The Other Wind',
      'author': 'Ursula K. Le Guin',
      'year': '2001',
      'description': '',
      'picture':''},
    {'title': 'Neuromancer',
      'author': 'William Gibson',
      'year': '1984',
      'description': '',
      'picture':''},
    {'title': 'Mistborn: The Final Empire',
      'author': 'Brandon Sanderson',
      'year': '2006',
      'description': '',
      'picture':''},
    {'title': 'Mistborn: The Well of Ascension',
      'author': 'Brandon Sanderson',
      'year': '2007',
      'description': '',
      'picture':''},
    {'title': 'Mistborn: The Hero of Ages',
      'author': 'Brandon Sanderson',
      'year': '2008',
      'description': '',
      'picture':''},
    {'title': 'Mistborn: The Alloy of Law',
      'author': 'Brandon Sanderson',
      'year': '2011',
      'description': '',
      'picture':''},
    {'title': 'Mistborn: Shadows of Self',
      'author': 'Brandon Sanderson',
      'year': '2015',
      'description': '',
      'picture':''},
    {'title': 'Mistborn: The Bands of Mourning',
      'author': 'Brandon Sanderson',
      'year': '2016',
      'description': '',
      'picture':''},
    {'title': 'Mistborn: Secret History',
      'author': 'Brandon Sanderson',
      'year': '2016',
      'description': '',
      'picture':''},
    //////////////////////////////61 books
  ];

  //Saves all book info in firebase with the title of the book as the path for the information
  books.forEach((element) async{
    await db.collection("Books").doc(element['title']).set(element);
  });
}
/*final databaseReference = FirebaseDatabase.instance.reference();

void GetBook(String title) async{
  //Retrieve book table, add something to it, set the table
  print(title);

  //var bookTable = await databaseReference.child("Books");
  //var result = await bookTable.child("test").once();

  final DatabaseReference db = FirebaseDatabase().reference();

  final FirebaseApp app;
  //db.child('Books').once().then((result) => print('result = $result'));

  Map<String, int> temp = {
    'one': 1,
    'two': 2,
    'three': 3,
  };

  db.set(temp);

  print(title);
  //print(result);
}*/